In [1]:
import torch

##### 1. Создайте случайный FloatTensor размера 3x4x5

In [2]:
f = torch.rand(3, 4, 5)
f

tensor([[[0.3392, 0.4350, 0.6783, 0.0182, 0.3377],
         [0.4237, 0.6329, 0.2125, 0.8598, 0.9005],
         [0.4294, 0.7841, 0.3078, 0.7837, 0.0234],
         [0.0572, 0.4959, 0.9905, 0.0697, 0.3130]],

        [[0.9272, 0.2171, 0.4530, 0.4617, 0.8348],
         [0.8475, 0.0797, 0.5335, 0.0913, 0.0329],
         [0.4371, 0.4917, 0.2844, 0.1458, 0.3597],
         [0.4311, 0.1816, 0.3770, 0.1448, 0.7330]],

        [[0.8711, 0.3394, 0.2415, 0.8376, 0.4492],
         [0.0092, 0.7248, 0.8933, 0.4806, 0.6944],
         [0.1370, 0.9483, 0.0614, 0.5560, 0.1741],
         [0.8906, 0.8691, 0.7139, 0.1770, 0.7151]]])

##### 2. Выведите его форму (shape)

In [3]:
f.size()

torch.Size([3, 4, 5])

##### 3. Приведите его к форме 6х10

In [4]:
f = f.reshape(6, 10)

print(f)
print(f.size())

tensor([[0.3392, 0.4350, 0.6783, 0.0182, 0.3377, 0.4237, 0.6329, 0.2125, 0.8598,
         0.9005],
        [0.4294, 0.7841, 0.3078, 0.7837, 0.0234, 0.0572, 0.4959, 0.9905, 0.0697,
         0.3130],
        [0.9272, 0.2171, 0.4530, 0.4617, 0.8348, 0.8475, 0.0797, 0.5335, 0.0913,
         0.0329],
        [0.4371, 0.4917, 0.2844, 0.1458, 0.3597, 0.4311, 0.1816, 0.3770, 0.1448,
         0.7330],
        [0.8711, 0.3394, 0.2415, 0.8376, 0.4492, 0.0092, 0.7248, 0.8933, 0.4806,
         0.6944],
        [0.1370, 0.9483, 0.0614, 0.5560, 0.1741, 0.8906, 0.8691, 0.7139, 0.1770,
         0.7151]])
torch.Size([6, 10])


##### 4. Создайте случайный IntTensor размера 10

In [5]:
i = torch.randint(10,(10,))
i

tensor([7, 7, 3, 2, 1, 8, 8, 8, 6, 8])

##### 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [6]:
f * i

tensor([[2.3747, 3.0450, 2.0349, 0.0363, 0.3377, 3.3896, 5.0628, 1.6999, 5.1585,
         7.2044],
        [3.0056, 5.4887, 0.9234, 1.5674, 0.0234, 0.4577, 3.9674, 7.9241, 0.4180,
         2.5044],
        [6.4905, 1.5195, 1.3591, 0.9234, 0.8348, 6.7796, 0.6379, 4.2682, 0.5481,
         0.2629],
        [3.0595, 3.4421, 0.8532, 0.2916, 0.3597, 3.4485, 1.4532, 3.0157, 0.8687,
         5.8636],
        [6.0980, 2.3758, 0.7245, 1.6752, 0.4492, 0.0734, 5.7985, 7.1466, 2.8835,
         5.5548],
        [0.9592, 6.6384, 0.1841, 1.1120, 0.1741, 7.1246, 6.9528, 5.7115, 1.0619,
         5.7207]])

##### 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [7]:
ff = torch.mm(f, f.T)
ff

tensor([[3.0541, 1.6080, 1.6375, 1.8414, 2.4647, 2.4447],
        [1.6080, 2.8418, 1.7223, 1.5111, 2.8771, 2.6865],
        [1.6375, 1.7223, 3.0408, 1.6267, 2.3614, 2.0074],
        [1.8414, 1.5111, 1.6267, 1.5835, 1.9509, 2.0480],
        [2.4647, 2.8771, 2.3614, 1.9509, 3.8723, 2.8574],
        [2.4447, 2.6865, 2.0074, 2.0480, 2.8574, 3.8622]])

In [8]:
ff.size()

torch.Size([6, 6])

##### 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [9]:
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)

In [10]:
y = x**3 + z - 75*t
y

tensor(-148.5000, grad_fn=<SubBackward0>)

In [11]:
y.backward()

In [12]:
x.grad

tensor(3.)

In [13]:
z.grad

tensor(1.)

In [14]:
t.grad

tensor(-75.)

##### 8. Создайте единичный тензор размера 5x6

In [15]:
o = torch.ones((5, 6))
o

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

##### 9. Переведите его в формат numpy

In [16]:
o.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)